language: dart
sudo: false
dart:
  - "dev"
  - "stable"
  - "2.1.0"

dart_task:
  - dartanalyzer: '--fatal-warnings lib/ test/'
  - test: --platform vm
  - test: --platform firefox
  - dartfmt

matrix:
  allow_failures:
    - dart: "dev"